// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL97ZY81X9JPJ6sxJ76MpnV-Gxr5C3yJI',
    appId: '1:156569762365:web:9bff0dae2ff2bbe67f8854',
    messagingSenderId: '156569762365',
    projectId: 'member-futsal',
    authDomain: 'member-futsal.firebaseapp.com',
    storageBucket: 'member-futsal.appspot.com',
    measurementId: 'G-9P4PCVP2GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyN778El7CZ3keiP2qvcwZjF_Iq55Tak',
    appId: '1:156569762365:android:f8ef2c13258b9b327f8854',
    messagingSenderId: '156569762365',
    projectId: 'member-futsal',
    storageBucket: 'member-futsal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNrT3H6ywETnOEkXN2jNgtp4VhYBk-CuE',
    appId: '1:156569762365:ios:8e08cc7a602948f97f8854',
    messagingSenderId: '156569762365',
    projectId: 'member-futsal',
    storageBucket: 'member-futsal.appspot.com',
    iosClientId: '156569762365-0nan020smrikj587624k1fko8pptquuf.apps.googleusercontent.com',
    iosBundleId: 'com.kodenatan.member-futsal.memberFutsal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNrT3H6ywETnOEkXN2jNgtp4VhYBk-CuE',
    appId: '1:156569762365:ios:8e08cc7a602948f97f8854',
    messagingSenderId: '156569762365',
    projectId: 'member-futsal',
    storageBucket: 'member-futsal.appspot.com',
    iosClientId: '156569762365-0nan020smrikj587624k1fko8pptquuf.apps.googleusercontent.com',
    iosBundleId: 'com.kodenatan.member-futsal.memberFutsal',
  );
}
